server:
    port: 8080
spring:
    profiles:
        active: dev
        spring:
            h2:
                console:
                    enabled: true
                    path: /h2-console

    datasource:
        url: jdbc:h2:./db_dev;MODE=MySQL
        username: sa
        password:
        driver-class-name: org.h2.Driver

    output:
        ansi:
            enabled: always

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100
                highlight-sql: true

    jackson:
        serialization:
            fail-on-empty-beans: false


logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
        org.hibernate.orm.jdbc.extract: TRACE
        org.springframework.security: DEBUG