name: Run Tests Before Merging

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application-secret.yml from GitHub Secrets
        run: |
          envsubst < src/main/resources/application-template.yml > src/main/resources/application-secret.yml
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Build and run tests
        run: |
          ./gradlew build --no-daemon
          ./gradlew test
